### PR TITLE
ExDoc now uses Makeup for syntax highlighting

### PR DESCRIPTION
**Pull request by tmbb**
By default, ExDoc uses a Javascript library for syntax highlighting
of code examples. The syntax highlighting is bad in general,
and particularly bad in some specific cases, like structures.

Makeup fixes many cases that were broken in the Javascript version,
and adds some niceties of its own, like highlighting matching delimiters
on mouseover.

Besides, except for the matching delimiters, Makeup doesn't require
Javascript, and the code is rendered into static HTML and CSS.

To build the docs:

```
MIX_ENV=docs mix docs
```

Is you want, I can change it so that you don't need to set `MIX_ENV=docs`, I only did it like this because you already have a `config/docs.exs` file.

### CODE REVIEW

**Comment by grych** [comment]
Good point!

**Comment by tmbb** [comment]
Please don't merge this right now. Makedown has a nasty bug when highlighting code that's not elixir code (i.e. HTML, drab templates, etc). I'll fix it as soon as possible.

**Comment by tmbb** [comment]
> Good point!

So you prefer `dev`?

**Comment by grych** [comment]
> So you prefer dev?
Yes, as @OvermindDL1 mentioned, I publish to hex in dev.

**Comment by tmbb** [comment]
Ok. On the other hand, I've submitted a PR just like this to ecto, and @josevalim is worried about the fact that this has a large number of dependencies: https://github.com/elixir-ecto/ecto/pull/2264#discussion_r142973392

As I explain in that discussion, highlighting Elixir code well takes a lot of code, and there is really no way around it (doing it in Javascript, as ExDoc's doing now is just sweeping the problem under the rug). I think Makeup is realy much better than the Javascript at highlighting the code, and I think the extra dependencies are worth it.

**Comment by tmbb** [comment]
Fixed upstream bug.

**Comment by tmbb** [comment]
Meanwhile, you can browse the docs rendered by `makedown` here: https://tmbb.github.io/drab/Drab.html

**Comment by grych** [comment]
Looks good at the first, very quick, glance, the only what I don't like is how it treats EEx injections with `<%= %>` - it is coloring the percent sign differently.

I will put it on hold for the same reason as [here](https://github.com/elixir-ecto/ecto/pull/2264#issuecomment-334576089).

**Comment by tmbb** [comment]
> he only what I don't like is how it treats EEx injections with <%= %> - it is coloring the percent sign differently.

That's not a problem with Makwdown, it's a problem with your docs ;) You didn't specify a programming language for those code blocks, so Makedown assumes Elixir. They are actually EEx, and as such Makedown "fails" spectacularly. The default JS highlighter, highlight.js, assumes Elixir too, but because it color operators in black (Makedown's them colors them orange) and is generally crappy, you don't notice.

There is an HTML lexer for Makeup that might give you better results. You can also tag those code blocks as HTML so that they are handled by highlight.js.

I plan on having a Makeup lexer for EEx HTML templates relatively soon (about two months, I guess?), and I plan on shipping the documentation tool by default with support for Elixir, EEx and HTML (probably not CSS and probably not JS). For other languages, as long as you tag the block with the corresponding pogrammin language, highlight.js will try its best.

**Comment by tmbb** [comment]
There is now a new package named `ex_doc_makeup` that simplifies the process considerably. It also has no dependencies besides `ex_doc`, `ex_spirit` and `makeup` (and `makeup_elixir`, of course). I'd submit a PR but actually I prefer you add it yourself to see if the docs are clear.

**Comment by tmbb** [comment]
PS: It'll make the HTML and EEx in the docs look worse unless you explicitly tag them as HTML

**Comment by grych** [comment]
Still not convinced. You should rather try to change the ExDoc, so you library would be standard for all docs.

Closing.

**Comment by OvermindDL1** [comment]
> Still not convinced. You should rather try to change the ExDoc, so you library would be standard for all docs.

Excluding this PR, in ex_doc itself it by default uses markdown, you really need to tag the type of the text fields properly or color highlighting will fail in other modes too.  ^.^

**Pull request closed without merging**
