### PR TITLE
add Drab.Element.replace_html/3

### PR DESCRIPTION
**Pull request by bougueil**

### CODE REVIEW

**Comment by grych** [comment]
What is the difference between `replace_html` and 

    set_prop socket, "selector", innerHTML: "new html" 

?

**Comment by bougueil** [comment]
don't know the difference
just tried your alternative that doesn't work for me

set_prop socket, "#pen1", innerHTML: "<a id='id'>replaced_link</a>"  # NOK

replace_html socket, "#pen1",  "<a id='id'>replaced_link</a>"  # id
successfully replaced

however replace_html is more meaningful isn't it ?

awesome work !

**Comment by grych** [comment]
Please try:

    set_prop socket, "#pen1", outerHTML: "<a id='id'>replaced_link</a>"

as your `replace_html` is working on outerHTML property. Should be the same.

Accually, I don't want to introduce too many functions to `Drab.Element`, as we may finish building another jQuery :) Only the necessary. If we add `replace_html`, we should do the same for `replace_text`, `replace_inner_html`, etc etc. 

Closing. Thanks for the PR anyway 👍

**Comment by bougueil** [comment]
yes

**Pull request closed without merging**
